name: Upload Images
on: [workflow_dispatch, repository_dispatch, push]
jobs:
  image-export:
    env:
      FIGMA_TOKEN: ${{secrets.FIGMA_TOKEN}}
      FIGMA_FILE_URL: https://www.figma.com/file/Pez6alDW7c8sbeRWHtjq2U/Game-Logos
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Export Figma images
        uses: ./.github/actions/figma-export

